// components/tools/toolViz/Histogram.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import * as d3 from "d3";

const MARGIN = { top: 30, right: 30, bottom: 40, left: 50 };
const BUCKET_NUMBER = 70;
const BUCKET_PADDING = 1;

type d_bin = typeof d3.bins[number];

export default function Histogram({ data, xLabel = "", yLabel = "" }) {

  const [dimensions, setDimensions] = useState({ width: 300, height: 300 });

  const svgRef = useRef(null);
  const parentRef = useRef(null);

  const getSvgContainerSize = () => {
    const newWidth = parentRef.current.clientWidth;
    const newHeight = parentRef.current.clientHeight;
    setDimensions({ width: newWidth, height: newHeight });
  };

  useEffect(() => {
    getSvgContainerSize();
    window.addEventListener("resize", getSvgContainerSize);

    return () => window.removeEventListener("resize", getSvgContainerSize);
  }, []);

  if (dimensions.width === 0 && dimensions.height === 0){
    getSvgContainerSize();
  }

  const width = dimensions.width;
  const height = Math.min(dimensions.height, window.innerHeight - 100);

  const boundsWidth = width - 100 - MARGIN.right - MARGIN.left;
  const boundsHeight = height - MARGIN.top - MARGIN.bottom;

  // Create X scale based on the data
  const xScale = useMemo(() => {
    const max = Math.max(...data);
    const min = Math.min(...data);
    return d3
      .scaleLinear()
      .domain([min - min * 0.04, max + max * 0.04])
      .range([0, boundsWidth]);
  }, [data, boundsWidth]);

  // Create a bucket generator for the histogram
  const bucketGenerator = useMemo(() => {
    return d3
      .bin()
      .value((d: d_bin) => d)
      .domain(xScale.domain())
      .thresholds(xScale.ticks(BUCKET_NUMBER));
  }, [xScale]);

  // Generate histogram buckets based on the data
  const buckets = useMemo(() => bucketGenerator(data), [bucketGenerator, data]);

  // Create Y scale based on the histogram buckets
  const yScale = useMemo(() => {
    const max = d3.max(buckets, (bucket: d_bin) => bucket.length);
    return d3.scaleLinear().range([boundsHeight, 0]).domain([0, max || 0]).nice();
  }, [buckets, boundsHeight]);

  // Effect to update the chart when the scales or data change
  // Effect to update the chart when the scales or data change
  useEffect(() => {
    // Select the SVG element
    const svgElement = d3.select(svgRef.current);

    // Remove existing elements within the SVG
    svgElement.selectAll("*").remove();

    // Create X-axis and position it
    const xAxisGenerator = d3.axisBottom(xScale);
    svgElement
      .append("g")
      .attr("transform", `translate(${MARGIN.left},${height - MARGIN.bottom})`)
      .call(xAxisGenerator);

    // Add X-axis label
    svgElement
      .append("text")
      .attr("transform", `translate(${width / 2},${height - MARGIN.bottom + 30})`)
      .style("text-anchor", "middle")
      .text(xLabel);

    // Create Y-axis and position it
    const yAxisGenerator = d3.axisLeft(yScale);
    svgElement
      .append("g")
      .attr("transform", `translate(${MARGIN.left},${MARGIN.top})`)
      .call(yAxisGenerator);

    // Add Y-axis label
    svgElement
      .append("text")
      .attr("transform", "rotate(-90)")
      .attr("y", MARGIN.left - 40)
      .attr("x", 0 - height / 2)
      .attr("dy", "1em")
      .style("text-anchor", "middle")
      .text(yLabel);

    svgElement
      .append("g")
      .attr("transform", `translate(${MARGIN.left},${MARGIN.top})`)
      .selectAll("rect")
      .data(buckets)
      .join("rect")
      .attr("x", (d: d_bin) => xScale(d.x0) + BUCKET_PADDING / 2)
      .attr("width", (d: d_bin) => Math.max(0, xScale(d.x1) - xScale(d.x0) - BUCKET_PADDING))
      .attr("y", (d: d_bin) => yScale(d.length))
      .attr("height", (d: d_bin) => boundsHeight - yScale(d.length))
      .attr("fill", "#69b3a2");
  }, [xScale, yScale, buckets, dimensions]);


  if (data === undefined) {
    return (
      <></>
    )
  } else {
    return (
      <div className="container" ref={parentRef}>
        <svg width={width} height={height} ref={svgRef}>
          <g ref={svgRef}>
          </g>
        </svg>
      </div>
    );
  }

}

// src/lib/components/ui/Histogram.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import * as d3 from 'd3';
	import { browser } from '$app/environment';

	export let data: number[] = [];
	export let xLabel: string;
	export let yLabel: string;
	export let act_col: string;

	let processedData: number[] = [];
	let width: number = 0,
		height: number = 0;
	let svg: SVGSVGElement | null = null;
	let binNumber = 100; // Default bin count

	$: processedData = data
		.filter((datum) => datum.hasOwnProperty(act_col)) // Check if act_col exists
		.map((datum) => datum[act_col]);
	const updateSize = () => {
		if (!browser) return;
		const container = document.getElementById('histogram-container');
		if (!container) return;

		width = container.offsetWidth;
		height = container.offsetHeight;

		// Adjust bin number dynamically based on screen size
		binNumber = width < 600 ? 20 : 100; // Reduce bins for small screens

		renderChart();
	};

	const renderChart = () => {
		if (!svg || !browser) return;

		d3.select(svg).selectAll('*').remove();
		const margin = { top: 20, right: 30, bottom: 80, left: 80 };

		const svgElement = d3
			.select(svg)
			.attr('width', width)
			.attr('height', height)
			.append('g')
			.attr('transform', `translate(${margin.left},${margin.top})`);

		const x = d3
			.scaleLinear()
			.domain([0, d3.max(processedData) ?? 0])
			.range([0, width - margin.left - margin.right]);

		const bins = d3.bin().domain(x.domain()).thresholds(binNumber)(processedData);

		const y = d3
			.scaleLinear()
			.domain([0, d3.max(bins, (d) => d.length) ?? 0])
			.range([height - margin.top - margin.bottom, 0]);

		svgElement
			.selectAll('.bar')
			.data(bins)
			.enter()
			.append('rect')
			.attr('class', 'bar')
			.attr('x', (d) => x(d.x0 ?? 0))
			.attr('y', (d) => y(d.length))
			.attr('width', (d) => x(d.x1 ?? 0) - x(d.x0 ?? 0) - 1)
			.attr('height', (d) => height - margin.top - margin.bottom - y(d.length))
			.attr('fill', 'steelblue');

		svgElement
			.append('g')
			.attr('transform', `translate(0,${height - margin.top - margin.bottom})`)
			.call(d3.axisBottom(x).tickSize(10).tickPadding(10))
			.selectAll('text')
			.style('font-size', '18px')
			.style('fill', 'currentColor');

		svgElement
			.append('g')
			.call(d3.axisLeft(y).tickSize(10).tickPadding(10))
			.selectAll('text')
			.style('font-size', '18px')
			.style('fill', 'currentColor');

		svgElement
			.append('text')
			.attr(
				'transform',
				`translate(${(width - margin.left - margin.right) / 2}, ${height - margin.top - margin.bottom + 70})`
			)
			.style('text-anchor', 'middle')
			.style('font-size', '22px')
			.style('fill', 'currentColor')
			.text(xLabel);

		svgElement
			.append('text')
			.attr('transform', 'rotate(-90)')
			.attr('y', -margin.left + 20)
			.attr('x', -(height - margin.top - margin.bottom) / 2)
			.style('text-anchor', 'middle')
			.style('font-size', '22px')
			.style('fill', 'currentColor')
			.text(yLabel);
	};

	$: {
		if (processedData.length > 0 && browser) {
			renderChart();
		}
	}

	onMount(() => {
		if (!browser) return;
		window.addEventListener('resize', updateSize);
		updateSize();
	});

	onDestroy(() => {
		if (!browser) return;
		window.removeEventListener('resize', updateSize);
	});
</script>

<span>Total Number of Molecules Being Shown on The Histogram: {processedData.length}</span>
<div id="histogram-container">
	<svg bind:this={svg}></svg>
</div>

<style>
	#histogram-container {
		width: 100%;
		height: 75vh;
	}
</style>
